// <auto-generated />
using System;
using Code_Fidus_CsharpAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Code_Fidus_CsharpAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Code_Fidus_CsharpAPI.Models.accounts", b =>
                {
                    b.Property<int>("account_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("account_id");

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("Code_Fidus_CsharpAPI.Models.answars", b =>
                {
                    b.Property<int>("answar_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.Property<string>("answar_content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("answar_time")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("post_id")
                        .HasColumnType("int");

                    b.HasKey("answar_id");

                    b.ToTable("answars");
                });

            modelBuilder.Entity("Code_Fidus_CsharpAPI.Models.categories", b =>
                {
                    b.Property<int>("category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("catname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("picture")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("category_id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("Code_Fidus_CsharpAPI.Models.faqs", b =>
                {
                    b.Property<int>("follow_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.Property<string>("faq_content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("faq_created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("faq_title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("faq_updated_date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("follow_id");

                    b.ToTable("faqs");
                });

            modelBuilder.Entity("Code_Fidus_CsharpAPI.Models.follows", b =>
                {
                    b.Property<int>("follow_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.HasKey("follow_id");

                    b.ToTable("follows");
                });

            modelBuilder.Entity("Code_Fidus_CsharpAPI.Models.loginhistories", b =>
                {
                    b.Property<int>("follow_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("login_time")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("logout_time")
                        .HasColumnType("datetime(6)");

                    b.HasKey("follow_id");

                    b.ToTable("loginhistories");
                });

            modelBuilder.Entity("Code_Fidus_CsharpAPI.Models.messages", b =>
                {
                    b.Property<int>("message_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("from_account_id")
                        .HasColumnType("int");

                    b.Property<bool>("readornot")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("send_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("subject")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("to_account_id")
                        .HasColumnType("int");

                    b.HasKey("message_id");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("Code_Fidus_CsharpAPI.Models.motds", b =>
                {
                    b.Property<int>("motd_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.Property<string>("context")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("motd_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("motd_id");

                    b.ToTable("motds");
                });

            modelBuilder.Entity("Code_Fidus_CsharpAPI.Models.post_types", b =>
                {
                    b.Property<int>("post_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("post_type_title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("post_type_id");

                    b.ToTable("post_types");
                });

            modelBuilder.Entity("Code_Fidus_CsharpAPI.Models.posts", b =>
                {
                    b.Property<int>("post_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<string>("post_content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("post_headline")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("post_time")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("post_type_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("post_update")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("post_views")
                        .HasColumnType("int");

                    b.HasKey("post_id");

                    b.ToTable("posts");
                });

            modelBuilder.Entity("Code_Fidus_CsharpAPI.Models.profiles", b =>
                {
                    b.Property<int>("profile_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("information")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("picture")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("secondname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("worktitle")
                        .HasColumnType("int");

                    b.HasKey("profile_id");

                    b.ToTable("profiles");
                });

            modelBuilder.Entity("Code_Fidus_CsharpAPI.Models.roles", b =>
                {
                    b.Property<int>("role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("role_id");

                    b.ToTable("roles");
                });
#pragma warning restore 612, 618
        }
    }
}
